rubybox:
  # Replace image by build if you want to customize the ruby vm
  # build: .
  image: ruby:2.3
  command: bash
  working_dir: /usr/src/app
  environment:
    BUNDLE_PATH: 'vendor/bundle'
  # Uncomment ports config if needed
  #  PORT: 8080
  # ports:
  #   - '8080:8080'
  volumes:
    - '.:/usr/src/app'
